// .vuepress/vuepress-pdf.config.ts
import { defineUserConfig } from "@condorhero/vuepress-plugin-export-pdf-v2";

export default defineUserConfig({
  outDir: "docs/.vuepress/dist/",
  sorter: (pageA, pageB) => {
    const aIndex = routeOrder.findIndex(route => route === pageA.path)
    const bIndex = routeOrder.findIndex(route => route === pageB.path)
    return aIndex - bIndex
  },
  pdfOptions: {
    format: 'A4',
    displayHeaderFooter: true,
    headerTemplate,
    footerTemplate,
    margin: {
      bottom: 70,
      left: 25,
      right: 25,
      top: 70,
    },
  },
});

const routeOrder = [
		'/README.html',
		'/SUMMARY.html',
		'/di-0-zhang-freebsd-zhong-wen-she-qu/di-0.1-jie-freebsd-faq.html',
		'/di-0-zhang-freebsd-zhong-wen-she-qu/di-0.2-jie-freebsd-zhong-wen-she-qu-cfc-fa-zhan-gui-hua.html',
		'/di-0-zhang-freebsd-zhong-wen-she-qu/di-0.3-jie-freebsd-de-bu-zu-zhi-chu.html',
		'/di-0-zhang-freebsd-zhong-wen-she-qu/di-0.4-jie-freebsd-fa-hang-shuo-ming.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.1-jie-shi-mo-shi-unix.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.2-jie-shi-mo-shi-unixlike.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.3-jie-shi-mo-shi-linux.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.4-jie-freebsd-yu-qi-ta-cao-zuo-xi-tong.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.5-jie-wei-shi-mo-yao-shi-yong-freebsd.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.6-jie-suo-wei-kai-yuan-zhe-xue.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.7-jie-qi-ta-bsd-jian-jie.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.8-jie-linux-yong-hu-qian-yi-zhi-bei.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.9-jie-can-kao-zi-liao-yu-gong-xian-zhe-ming-dan.html',
		'/di-1-zhang-zou-jin-freebsd/di-1.10-jie-bian-zhuan-shuo-ming.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.0-jie-tu-jie-an-zhuang.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.1-jie-san-zhong-xu-ni-ji-yu-freebsd-ban-ben-bi-jiao.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.2-jie-freebsd-13.0-an-zhuang-ji-yu-virtual-box.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.3-jie-freebsd-13.0-an-zhuang-ji-yu-vmware-workstation-pro.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.4-jie-teng-xun-yun-qing-liang-yun-ji-qi-ta-fu-wu-qi-dd-an-zhuang-freebsd.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.5-jie-shou-dong-an-zhuang-freebsd.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.6-jie-ee-yong-fa-ji-wang-luo-pei-zhi.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.7-jie-chang-yong-ruan-jian-yu-ssh-pei-zhi.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.8-jie-wu-li-ji-an-zhuang-yu-ying-jian-xuan-pei.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.9-jie-wu-li-ji-xia-xian-ka-de-pei-zhi.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.10-jie-wu-li-ji-xia-chu-mo-ban-de-she-zhi.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.11-jie-wu-li-ji-sheng-ka-yu-wang-ka-she-zhi.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.12-jie-da-yin-ji-de-an-zhuang.html',
		'/di-2-zhang-an-zhuang-freebsd/di-2.13-jie-wu-xian-lan-ya-shu-biao-de-she-zhi.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.0-jie-bao-guan-li-qi-gai-shu.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.1-jie-freebsd-jing-xiang-zhan-xian-zhuang.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.2-jie-freebsd-huan-yuan-fang-shi.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.3-jie-gitup-de-yong-fa.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.4-jie-ruan-jian-bao-guan-li-qi-pkg-de-yong-fa.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.5-jie-tong-guo-yuan-dai-ma-ports-fang-shi-an-zhuang-ruan-jian.html',
		'/di-3-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-3.6-jie-tong-guo-dvd-an-zhuang-ruan-jian.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.0-jie-gai-shu.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.1-jie-an-zhuang-xorg.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.2-jie-an-zhuang-kde-5.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.3-jie-an-zhuang-gnome.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.4-jie-an-zhuang-mate.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.5-jie-an-zhuang-xfce.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.6-jie-an-zhuang-cinnamon.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.7-jie-an-zhuang-lumina.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.8-jie-root-deng-lu-zhuo-mian.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.9-jie-zhu-ti-yu-mei-hua.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.10-jie-yuan-cheng-zhuo-mian-guan-li.html',
		'/di-4-zhang-zhuo-mian-an-zhuang/di-4.11-jie-an-zhuang-wayland-ke-xuan.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.1-jie-fcitx-shu-ru-fa-kuang-jia.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.2-jie-ibus-shu-ru-fa-kuang-jia.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.3-jie-wu-bi-shu-ru-fa.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.4-jie-firefox-yu-chromium-an-zhuang.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.5-jie-linux-jian-rong-ceng.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.6-jie-an-zhuang-jin-shan-wps.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.7-jie-an-zhuang-qq.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.8-jie-geng-huan-zi-ti.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.9-jie-wine.html',
		'/di-5-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-5.10-jie-ya-suo-yu-jie-ya.html',
		'/di-6-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-6.1-jie-ufs.html',
		'/di-6-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-6.2-jie-zfs.html',
		'/di-6-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-6.3-jie-ci-pan-kuo-rong.html',
		'/di-6-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-6.4-jie-ntfs-de-gua-zai.html',
		'/di-6-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-6.5-jie-swap-jiao-huan-fen-qu-de-she-zhi.html',
		'/di-6-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-6.6-jie-ext-234-deng-wen-jian-xi-tong.html',
		'/di-7-zhang-vpn-yu-dai-li/di-7.1-jie-http-dai-li.html',
		'/di-7-zhang-vpn-yu-dai-li/di-7.2-jie-v2ray.html',
		'/di-7-zhang-vpn-yu-dai-li/di-7.3-jie-clash.html',
		'/di-7-zhang-vpn-yu-dai-li/di-7.4-jie-openvpn.html',
		'/di-7-zhang-vpn-yu-dai-li/di-7.5-jie-wireguard.html',
		'/di-8-zhang-yong-hu-yu-quan-xian/di-8.1-jie-sudo.html',
		'/di-8-zhang-yong-hu-yu-quan-xian/di-8.2-jie-tian-jia-yong-hu.html',
		'/di-8-zhang-yong-hu-yu-quan-xian/di-8.3-jie-zu.html',
		'/di-8-zhang-yong-hu-yu-quan-xian/di-8.4-jie-yong-hu-quan-xian.html',
		'/di-9-zhang-jail/di-9.1-jie-jail-yu-docker-de-bi-jiao.html',
		'/di-9-zhang-jail/di-9.2-jie-jail-xiang-guan-shu-yu.html',
		'/di-9-zhang-jail/di-9.3-jie-jail-pei-zhi.html',
		'/di-9-zhang-jail/di-9.4-jie-jail-geng-xin.html',
		'/di-9-zhang-jail/di-9.5-jie-shi-yong-ezjail-guan-li-jail.html',
		'/di-10-zhang-xu-ni-hua/di-10.1-jie-xu-ni-hua-jian-jie.html',
		'/di-10-zhang-xu-ni-hua/di-10.2-jie-an-zhuang-virtual-box.html',
		'/di-10-zhang-xu-ni-hua/di-10.3-jie-an-zhuang-bhyve.html',
		'/di-10-zhang-xu-ni-hua/di-10.4-jie-shi-yong-cbsd-guan-li-bhyve.html',
		'/di-10-zhang-xu-ni-hua/di-10.5-jie-shi-yong-bhyve-an-zhuang-windows-10.html',
		'/di-10-zhang-xu-ni-hua/di-10.6-jie-an-zhuang-xen.html',
		'/di-10-zhang-xu-ni-hua/di-10.7-jie-shi-yong-xen-an-zhuang-windows.html',
		'/di-11-zhang-geng-xin-yu-sheng-ji-freebsd/di-11.1-jie-tong-guo-freebsdupdate-geng-xin.html',
		'/di-11-zhang-geng-xin-yu-sheng-ji-freebsd/di-11.2-jie-tong-guo-yuan-dai-ma-geng-xin.html',
		'/di-11-zhang-geng-xin-yu-sheng-ji-freebsd/di-11.3-jie-pi-liang-bu-shu.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.1-jie-gai-shu.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.2-jie-raid-0.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.3-jie-raid-1.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.4-jie-raid-3.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.5-jie-ruan-raid-pei-zhi.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.6-jie-geom-gate-wang-luo.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.7-jie-ci-pan-zhuang-zhi-biao-qian.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.8-jie-ufs-journaling-yu-geom.html',
		'/di-12-zhang-geom-cun-chu-kuang-jia/di-12.9-jie-zfs-ci-pan-jia-jie-mi.html',
		'/di-13-zhang-dtrace/di-13.1-jie-gai-shu.html',
		'/di-13-zhang-dtrace/di-13.2-jie-kai-qi-dtrace.html',
		'/di-13-zhang-dtrace/di-13.3-jie-shi-yong-dtrace.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.1-jie-ppp-bo-hao.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.2-jie-wifi.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.3-jie-usb-rndis-usb-wang-luo-gong-xiang.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.4-jie-lan-ya.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.5-jie-ipv6.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.6-jie-carp.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.7-jie-vlan.html',
		'/di-14-zhang-wang-luo-guan-li/di-14.8-jie-tcp-bbr.html',
		'/di-15-zhang-freebsd-fang-huo-qiang/di-15.1-jie-wang-luo-can-shu-pei-zhi-ming-ling.html',
		'/di-15-zhang-freebsd-fang-huo-qiang/di-15.2-jie-pf.html',
		'/di-15-zhang-freebsd-fang-huo-qiang/di-15.3-jie-ipfw.html',
		'/di-15-zhang-freebsd-fang-huo-qiang/di-15.4-jie-ipfilter-ipf.html',
		'/di-16-zhang-fu-wu-qi/di-16.1-jie-ftp-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.2-jie-dhcp-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.3-jie-nodejs-xiang-guan.html',
		'/di-16-zhang-fu-wu-qi/di-16.4-jie-dns-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.5-jie-nis-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.6-jie-postfix-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.7-jie-samba-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.8-jie-nfs-fu-wu-qi.html',
		'/di-16-zhang-fu-wu-qi/di-16.9-jie-iscsi.html',
		'/di-16-zhang-fu-wu-qi/di-16.10-jie-webmin.html',
		'/di-16-zhang-fu-wu-qi/di-16.11-jie-rsync-tong-bu-fu-wu.html',
		'/di-16-zhang-fu-wu-qi/di-16.12-jie-shi-jian-fu-wu.html',
		'/di-16-zhang-fu-wu-qi/di-16.13-jie-wildfly.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.1-jie-apache.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.2-jie-nginx.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.3-jie-php-8.x.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.4-jie-mysql-5.x.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.5-jie-mysql-8.x.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.6-jie-typecho.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.7-jie-ssl-pei-zhi.html',
		'/di-17-zhang-wang-luo-fu-wu-qi/di-17.8-jie-postgresql-yu-pgadmin4.html',
		'/di-18-zhang-shu-mei-pai-yu-qian-ru-shi/di-18.1-jie-shu-mei-pai-de-jian-jie.html',
		'/di-18-zhang-shu-mei-pai-yu-qian-ru-shi/di-18.2-jie-xi-tong-an-zhuang.html',
		'/di-18-zhang-shu-mei-pai-yu-qian-ru-shi/di-18.3-jie-shi-yong-pei-zhi.html',
		'/di-18-zhang-shu-mei-pai-yu-qian-ru-shi/di-18.4-jie-usb-wang-ka-yu-wifi.html',
		'/di-18-zhang-shu-mei-pai-yu-qian-ru-shi/di-18.5-jie-riscv.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.1-jie-wo-yu-freebsd-de-gu-shi.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.2-jie-freebsd-yu-mao-xuan-ze-1-de-sheng-huo.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.3-jie-linux-yu-ku-nan-zhe-xue.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.4-jie-cong-yi-ge-xiang-fa-kan-freebsd-shi-shang-ye-hua-huan-shi-xue-yuan-pai.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.5-jie-linux-she-qu-yi-jing-cheng-wei-le-yi-ge-ang-zang-de-ni-tan.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.6-jie-linux-bai-ju-yi-ding-bo-freebsd-da-bai-ju.html',
		'/di-19-zhang-wen-xue-gu-shi/di-19.7-jie-xiao-shuo-freebsd-cong-ru-men-dao-pao-lu.html',
		'/di-20-zhang-yu-le-yu-jiao-yu/di-20.1-jie-you-xi.html',
		'/di-20-zhang-yu-le-yu-jiao-yu/di-20.2-jie-yin-shi-pin-bo-fang-qi.html',
		'/di-20-zhang-yu-le-yu-jiao-yu/di-20.3-jie-yin-shi-pin-jian-ji.html',
		'/di-20-zhang-yu-le-yu-jiao-yu/di-20.4-jie-jiao-yu.html',
		'/di-20-zhang-yu-le-yu-jiao-yu/di-20.5-jie-ke-yan-yu-zhuan-ye-gong-ju.html',
		'/di-21-zhang-nei-he/di-21.1-jie-huo-qu-freebsd-nei-he-yuan-ma.html',
		'/di-21-zhang-nei-he/di-21.2-jie-xiu-gai-nei-he-yuan-ma.html',
		'/di-21-zhang-nei-he/di-21.3-jie-bian-yi-nei-he.html',
		'/di-21-zhang-nei-he/di-21.4-jie-nei-he-fen-xi.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.0-jie-ru-he-ding-yue-freebsd-de-you-jian-lie-biao.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.1-jie-ru-he-bao-gao-bug.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.2-jie-ru-he-ti-jiao-yi-ge-ruan-jian-bao.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.3-jie-ru-he-can-yu-freebsd-xie-zuo.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.4-jie-cc++-huan-jing-de-pei-zhi.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.5-jie-java-huan-jing-de-pei-zhi.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.6-jie-qt-huan-jing-de-pei-zhi.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.7-jie-python-yu-vscode.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.8-jie-rustgo-huan-jing-de-pei-zhi.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.9-jie-csh-yu-qi-ta-shell.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.10-jie-tong-guo-ida-7-tiao-shi-freebsd.html',
		'/di-22-zhang-bian-cheng-yu-kai-fa/di-22.11-jie-git.html',
		'/di-23-zhang-yin-dao-yu-hui-fu/di-23.1-jie-hui-fu-mo-shi-yu-mi-ma-zhong-zhi.html',
		'/di-23-zhang-yin-dao-yu-hui-fu/di-23.2-jie-freebsd-duo-ying-pan-efi-yin-dao-tong-yi.html',
		'/di-23-zhang-yin-dao-yu-hui-fu/di-23.3-jie-freebsd-zhong-wen-tty-kong-zhi-tai.html',
		'/di-23-zhang-yin-dao-yu-hui-fu/di-23.4-jie-yin-dao-jie-mian.html',
		'/di-23-zhang-yin-dao-yu-hui-fu/di-23.5-jie-grub-ji-qi-ta-yin-dao.html',
		'/di-24-zhang-freebsd-te-se/di-24.1-jie-bsd-init-guan-li-fu-wu.html',
		'/di-24-zhang-freebsd-te-se/di-24.2-jie-freebsd-mu-lu-jie-gou.html',
		'/di-24-zhang-freebsd-te-se/di-24.3-jie-bsdinstall-yu-bsdconfig.html',
		'/di-24-zhang-freebsd-te-se/di-24.4-jie-jin-yong-sendmail.html',
		'/di-24-zhang-freebsd-te-se/di-24.5-jie-li-yong-jiao-ben-zi-dong-sheng-cheng-bsdlibc-ku-wen-ben.html',
		'/di-24-zhang-freebsd-te-se/di-24.6-jie-bsd-feng-ge-de-makegrepsedawk.html',
		'/di-25-zhang-xi-tong-she-ji-yu-fen-xi/di-25.1-jie-freebsd-she-ji-gai-shu.html',
		'/di-25-zhang-xi-tong-she-ji-yu-fen-xi/di-25.2-jie-nei-he.html',
		'/di-25-zhang-xi-tong-she-ji-yu-fen-xi/di-25.3-jie-jin-cheng.html',
		'/di-25-zhang-xi-tong-she-ji-yu-fen-xi/di-25.4-jie-nei-cun-guan-li.html',
		'/di-25-zhang-xi-tong-she-ji-yu-fen-xi/di-25.5-jie-an-quan.html',
		'/di-25-zhang-xi-tong-she-ji-yu-fen-xi/di-25.6-jie-io-xi-tong.html',
		'/di-26-zhang-openbsd/di-26.0-jie-gai-shu.html',
		'/di-26-zhang-openbsd/di-26.1-jie-an-zhuang.html',
		'/di-26-zhang-openbsd/di-26.2-jie-pei-zhi.html',
		'/di-26-zhang-openbsd/di-26.3-jie-huan-yuan.html',
		'/di-26-zhang-openbsd/di-26.4-jie-bao-guan-li-qi.html',
		'/di-26-zhang-openbsd/di-26.5-jie-zhuo-mian-yu-qi-ta-ruan-jian.html',
		'/di-27-zhang-netbsd/di-27.0-jie-gai-shu.html',
		'/di-27-zhang-netbsd/di-27.1-jie-an-zhuang-yu-pei-zhi.html',
		'/di-27-zhang-netbsd/di-27.2-jie-huan-yuan-yu-bao-guan-li-qi.html',
		'/di-27-zhang-netbsd/di-27.3-jie-zhuo-mian-yu-qi-ta-ruan-jian.html',
		'/di-28-zhang-dragonflybsd/di-28.0-jie-gai-shu.html',
		'/di-28-zhang-dragonflybsd/di-28.1-jie-an-zhuang-yu-pei-zhi.html',
		'/di-29-zhang-zhuo-mian-gao-ji-jin-jie/di-29.0-jie-chuang-kou-guan-li-qi-yu-zhuo-mian-de-qu-bie-yu-lian-xi.html',
		'/di-29-zhang-zhuo-mian-gao-ji-jin-jie/di-29.1-jie-an-zhuang-i3wm.html',
		'/di-29-zhang-zhuo-mian-gao-ji-jin-jie/di-29.2-jie-an-zhuang-cde.html',
		'/di-29-zhang-zhuo-mian-gao-ji-jin-jie/di-29.3-jie-an-zhuang-awesome.html',
		'/di-29-zhang-zhuo-mian-gao-ji-jin-jie/di-29.4-jie-an-zhuang-fvwm.html',
    ]

const headerTemplate = `<div style="width: 100%; display: flex; justify-content: center; align-items: center; color: lightgray; border-bottom: solid lightgray 1px; padding-bottom: 10px; font-size: 10px;">
  <span class="title"></span>
</div>`

const footerTemplate = `<div style="width: 100%; display: flex; justify-content: center; align-items: center; color: lightgray; border-top: solid lightgray 1px; padding-top: 10px; font-size: 10px;">
  <span class="pageNumber"></span> - <span class="totalPages"></span>
</div>`
