name: Build and Deploy Webpages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3.0.2

      - name: Install project using Yarn
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build project using Yarn
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: docs:build

      - name: Upload built webpages to our web server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
          username: ${{ secrets.USERNAME }}
