name: Build and Deploy Webpages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Install project using Yarn
        uses: richard-chim/actions-yarn@v2.3.1
        with:
          cmd: install

      - name: Build project using Yarn
        uses: richard-chim/actions-yarn@v2.3.1
        with:
          cmd: docs:build

      - name: Upload built webpages to our web server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
          username: ${{ secrets.USERNAME }}
