name: Build and Deploy Webpages

on:
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Install project using Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build project using Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: docs:build

      - name: Upload built webpages to our web server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "docs/.vuepress/dist/*"
          target: "book-next/"
