name: Build and Deploy Webpages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
            
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build VuePress site
        run: yarn docs:build

      - name: Upload built webpages to our web server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
          username: ${{ secrets.USERNAME }}
